### ISSUE TITLE
Circle reference

### ISSUE THREAD

**Issue by halybang** [hexya-erp/hexya-addons#1]
-Module account's PostInit function call to pool.SaleReport().NewSet(env).Init(), which only available when enable sale module.
-Module sale also referred to module account.
Fix:
Move pool.SaleReport().NewSet(env).Init() to PostInit function of sale module.

**Comment by npiganeau** [comment]
You're right, it has nothing to do in account module.

Actually I have totally removed it since `Init()` methods are now called automatically at model bootstrap.
